load("//designer:build_pyuic5.bzl", "build_pyuic5")
#load("//designer:BUILD", "ALL_UIS")

build_pyuic5(
    name = "about_pyuic5",
    src = "//designer:about.ui",
    out = "about.py",
)

build_pyuic5(
    name = "addcards_pyuic5",
    src = "//designer:addcards.ui",
    out = "addcards.py",
)

build_pyuic5(
    name = "addfield_pyuic5",
    src = "//designer:addfield.ui",
    out = "addfield.py",
)

build_pyuic5(
    name = "addmodel_pyuic5",
    src = "//designer:addmodel.ui",
    out = "addmodel.py",
)

build_pyuic5(
    name = "addonconf_pyuic5",
    src = "//designer:addonconf.ui",
    out = "addonconf.py",
)

build_pyuic5(
    name = "addons_pyuic5",
    src = "//designer:addons.ui",
    out = "addons.py",
)

build_pyuic5(
    name = "browserdisp_pyuic5",
    src = "//designer:browserdisp.ui",
    out = "browserdisp.py",
)

build_pyuic5(
    name = "browseropts_pyuic5",
    src = "//designer:browseropts.ui",
    out = "browseropts.py",
)

build_pyuic5(
    name = "browser_pyuic5",
    src = "//designer:browser.ui",
    out = "browser.py",
)

build_pyuic5(
    name = "changemap_pyuic5",
    src = "//designer:changemap.ui",
    out = "changemap.py",
)

build_pyuic5(
    name = "changemodel_pyuic5",
    src = "//designer:changemodel.ui",
    out = "changemodel.py",
)

build_pyuic5(
    name = "clayout_top_pyuic5",
    src = "//designer:clayout_top.ui",
    out = "clayout_top.py",
)

build_pyuic5(
    name = "customstudy_pyuic5",
    src = "//designer:customstudy.ui",
    out = "customstudy.py",
)

build_pyuic5(
    name = "dconf_pyuic5",
    src = "//designer:dconf.ui",
    out = "dconf.py",
)

build_pyuic5(
    name = "debug_pyuic5",
    src = "//designer:debug.ui",
    out = "debug.py",
)

build_pyuic5(
    name = "dyndconf_pyuic5",
    src = "//designer:dyndconf.ui",
    out = "dyndconf.py",
)

build_pyuic5(
    name = "editaddon_pyuic5",
    src = "//designer:editaddon.ui",
    out = "editaddon.py",
)

build_pyuic5(
    name = "editcurrent_pyuic5",
    src = "//designer:editcurrent.ui",
    out = "editcurrent.py",
)

build_pyuic5(
    name = "edithtml_pyuic5",
    src = "//designer:edithtml.ui",
    out = "edithtml.py",
)

build_pyuic5(
    name = "exporting_pyuic5",
    src = "//designer:exporting.ui",
    out = "exporting.py",
)

build_pyuic5(
    name = "fields_pyuic5",
    src = "//designer:fields.ui",
    out = "fields.py",
)

build_pyuic5(
    name = "finddupes_pyuic5",
    src = "//designer:finddupes.ui",
    out = "finddupes.py",
)

build_pyuic5(
    name = "findreplace_pyuic5",
    src = "//designer:findreplace.ui",
    out = "findreplace.py",
)

build_pyuic5(
    name = "getaddons_pyuic5",
    src = "//designer:getaddons.ui",
    out = "getaddons.py",
)

build_pyuic5(
    name = "importing_pyuic5",
    src = "//designer:importing.ui",
    out = "importing.py",
)

build_pyuic5(
    name = "modelopts_pyuic5",
    src = "//designer:modelopts.ui",
    out = "modelopts.py",
)

build_pyuic5(
    name = "models_pyuic5",
    src = "//designer:models.ui",
    out = "models.py",
)

build_pyuic5(
    name = "preferences_pyuic5",
    src = "//designer:preferences.ui",
    out = "preferences.py",
)

build_pyuic5(
    name = "preview_pyuic5",
    src = "//designer:preview.ui",
    out = "preview.py",
)

build_pyuic5(
    name = "profiles_pyuic5",
    src = "//designer:profiles.ui",
    out = "profiles.py",
)

build_pyuic5(
    name = "progress_pyuic5",
    src = "//designer:progress.ui",
    out = "progress.py",
)

build_pyuic5(
    name = "reposition_pyuic5",
    src = "//designer:reposition.ui",
    out = "reposition.py",
)

build_pyuic5(
    name = "reschedule_pyuic5",
    src = "//designer:reschedule.ui",
    out = "reschedule.py",
)

build_pyuic5(
    name = "setgroup_pyuic5",
    src = "//designer:setgroup.ui",
    out = "setgroup.py",
)

build_pyuic5(
    name = "setlang_pyuic5",
    src = "//designer:setlang.ui",
    out = "setlang.py",
)

build_pyuic5(
    name = "stats_pyuic5",
    src = "//designer:stats.ui",
    out = "stats.py",
)

build_pyuic5(
    name = "studydeck_pyuic5",
    src = "//designer:studydeck.ui",
    out = "studydeck.py",
)

build_pyuic5(
    name = "taglimit_pyuic5",
    src = "//designer:taglimit.ui",
    out = "taglimit.py",
)

build_pyuic5(
    name = "template_pyuic5",
    src = "//designer:template.ui",
    out = "template.py",
)

build_pyuic5(
    name = "main_pyuic5",
    src = "//designer:main.ui",
    out = "main.py",
)

#build_all_uis(ALL_UIS)

# TODO: genrule(
# TODO:     name = "icons_genrule",
# TODO:     srcs = ["//designer:icons.qrc"],
# TODO:     outs = ["icons_rc.py"],
# TODO:     cmd = "pyrcc5 $(location //designer:icons.qrc) -o \"$@\"",
# TODO: )

#__init__.py
#main.py
